# Generated by Django 2.2.7 on 2019-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191127_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_size',
            new_name='pizza_size_1',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_size_2',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
