# Generated by Django 2.2.7 on 2019-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pizzashoppingcart_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzashoppingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
