# Generated by Django 2.2.7 on 2019-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pizzashoppingcart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topping_name', models.CharField(default='', max_length=128)),
                ('sub_topping_price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzatopping',
            name='pizza_topping_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
