# Generated by Django 2.2.7 on 2019-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_subshoppingcart_sub_topping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subshoppingcart',
            name='toppings',
            field=models.CharField(default='', max_length=128),
        ),
    ]
