# Generated by Django 2.2.7 on 2019-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191211_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='subshoppingcart',
            name='sub_final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
