# Generated by Django 2.2.7 on 2019-12-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_subshoppingcart_sub_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersubshoppingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
