# Generated by Django 2.2.7 on 2020-05-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_othersubshoppingcart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersubshoppingcart',
            name='other_sub',
        ),
        migrations.RemoveField(
            model_name='othersubshoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pastashoppingcart',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='pastashoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pizzashoppingcart',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizzashoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saladshoppingcart',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='saladshoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subshoppingcart',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='subshoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='DinnerShoppingCart',
        ),
        migrations.DeleteModel(
            name='OtherSubShoppingCart',
        ),
        migrations.DeleteModel(
            name='PastaShoppingCart',
        ),
        migrations.DeleteModel(
            name='PizzaShoppingCart',
        ),
        migrations.DeleteModel(
            name='SaladShoppingCart',
        ),
        migrations.DeleteModel(
            name='SubShoppingCart',
        ),
    ]
