# Generated by Django 2.2.7 on 2020-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='', max_length=128)),
                ('user', models.CharField(default='', max_length=128)),
                ('itemSize', models.CharField(default='', max_length=128)),
                ('itemToppings', models.CharField(default='', max_length=128)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
