# Generated by Django 2.2.7 on 2020-05-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200515_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='order_time',
            field=models.CharField(default='', max_length=128),
        ),
    ]
