# Generated by Django 2.2.7 on 2020-05-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200519_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
