# Generated by Django 2.2.7 on 2020-05-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmed', models.BooleanField(default=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='order_confirmed',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='order_time',
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shape', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.CharField(blank=True, max_length=128, null=True)),
                ('toppings_number', models.IntegerField(default=0)),
                ('toppings', models.ManyToManyField(to='orders.Toppings')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.MenuItemType')),
            ],
        ),
    ]
