# Generated by Django 2.2.7 on 2020-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200528_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
