# Generated by Django 2.2.7 on 2020-05-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200528_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='toppings',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.MenuItem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
            ],
        ),
    ]
