# Generated by Django 2.2.7 on 2020-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200528_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='toppings_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
