# Generated by Django 2.2.7 on 2020-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200530_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
