# Generated by Django 2.2.7 on 2020-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200530_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
