# Generated by Django 2.2.7 on 2020-05-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_menuitem_menu_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='OtherSub',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaTopping',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='SubTopping',
        ),
    ]
