# Generated by Django 2.2.7 on 2020-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20200628_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
