# Generated by Django 2.2.7 on 2020-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_orderitem_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='added_time',
            field=models.DateTimeField(),
        ),
    ]
