# Generated by Django 2.2.7 on 2020-07-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20200702_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='added_time',
        ),
    ]
